from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False, slow_mo=50)
    page = browser.new_page()
    page.goto("https://www.saucedemo.com/")
    page.fill("#user-name", "standard_user")
    page.fill("#password", "secret_sauce")
    page.click("#login-button")
    page.screenshot(path="./screenshot/example.png", full_page=True)
    page.click("#add-to-cart-sauce-labs-backpack")
    page.click("#add-to-cart-sauce-labs-bike-light")
    page.click("#add-to-cart-sauce-labs-bolt-t-shirt")
    page.click("#shopping_cart_container")
    page.screenshot(path="./screenshot/examplecart.png", full_page=True)
    page.click("#checkout")
    page.fill("#first-name", "John")
    page.fill("#last-name", "Doe")
    page.fill("#postal-code", "12345")
    page.screenshot(path="./screenshot/examplecheckout.png", full_page=True)
    page.click("#continue")
    page.screenshot(path="./screenshot/exampleconfirmation.png",
                    full_page=True)
    page.click("#finish")
    page.screenshot(path="./screenshot/examplefinish.png", full_page=True)
    page.click("#back-to-products")
    page.screenshot(path="./screenshot/exampleback.png", full_page=True)
